export const PRODUCTS = [
  {
    id: 'cross-silver',
    name: 'God Is Love Cross',
    subtitle: '3 Variants · Key Cross',
    category: 'crosses',
    price: 12.30,
    images: ['/media/cross-product.png'],
    description: 'A 3D-printed key cross bearing "GOD IS" and the scripture "1 JOHN 4:8." Available in 3 styles: Blue & Red, Silver, and Grey & Yellow.',
    customizable: false,
    badge: '3 Variants',
    scent: null,
  },
  {
    id: 'cross-plain',
    name: 'Plain Cross',
    subtitle: 'Key Cross · No Lettering',
    category: 'crosses',
    price: 12.30,
    images: ['/media/cross-product.png'],
    description: 'A clean, molded key cross with the signature key-shaped bottom — no lettering. A simple, professional statement of faith.',
    customizable: false,
    badge: 'Plain',
    scent: null,
  },
  {
    id: 'betta-plain',
    name: 'Betta Body Butta',
    subtitle: 'Plain · 8 oz jar',
    category: 'body-care',
    price: 20,
    images: ['/media/body-butta-jar.png'],
    description: 'Great for dry hair, scalp, cracked heels, knees, elbows, eczema, psoriasis, scars, stretch marks, wrinkles, and more. Handcrafted with care in Jackson, MS. Contains nut oils.',
    customizable: false,
    badge: 'Handcrafted',
    scent: 'Plain',
  },
  {
    id: 'betta-savage',
    name: 'Betta Body Butta',
    subtitle: 'Sauvage · 8 oz jar',
    category: 'body-care',
    price: 20,
    images: ['/media/body-butta-jar.png'],
    description: 'Great for dry hair, scalp, cracked heels, knees, elbows, eczema, psoriasis, scars, stretch marks, wrinkles, and more. Handcrafted with care in Jackson, MS. Contains nut oils.',
    customizable: false,
    badge: 'Handcrafted',
    scent: 'Sauvage',
  },
  {
    id: 'betta-vanilla',
    name: 'Betta Body Butta',
    subtitle: 'Vanilla Berry · 8 oz jar',
    category: 'body-care',
    price: 20,
    images: ['/media/body-butta-jar.png'],
    description: 'Great for dry hair, scalp, cracked heels, knees, elbows, eczema, psoriasis, scars, stretch marks, wrinkles, and more. Handcrafted with care in Jackson, MS. Contains nut oils.',
    customizable: false,
    badge: 'Handcrafted',
    scent: 'Vanilla Berry',
  },
  {
    id: 'betta-power',
    name: 'Betta Body Butta',
    subtitle: 'Powder · 8 oz jar',
    category: 'body-care',
    price: 20,
    images: ['/media/body-butta-jar.png'],
    description: 'Great for dry hair, scalp, cracked heels, knees, elbows, eczema, psoriasis, scars, stretch marks, wrinkles, and more. Handcrafted with care in Jackson, MS. Contains nut oils.',
    customizable: false,
    badge: 'Handcrafted',
    scent: 'Powder',
  },
];

export const getProduct = (id) => PRODUCTS.find((p) => p.id === id);